- name: Install Crontab
  apt:
    name: cron
    state: present
    update_cache: yes
  become: true

- name: Ensure Crontab is enabled and started
  systemd:
    name: cron
    enabled: yes
    state: started
