services:
  parser:
    image: parser_app:latest
    container_name: parser
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0:0"
    volumes:
      - .:/app
    environment:
      - ...
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: '4000M'
    networks:
      - default

  promtail_parser:
    image: grafana/promtail:latest
    container_name: promtail_parser
    volumes:
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
    restart: always
    networks:
      - default


networks:
  default:
    external: true
    name: parser_network
