services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "0:0"
    volumes:
      - redis-data:/data

  worker:
    container_name: worker
    image: worker:latest
    build:
      context: .
      dockerfile: tasks/Dockerfile
    environment:
      - ...
    depends_on:
      - redis

  app:
    container_name: app
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ...
    depends_on:
      - redis
      - worker


volumes:
  redis-data:
