global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    metrics_path: /cadvisor/metrics
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'docker-containers'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [ __meta_docker_container_name ]
        target_label: name
      - action: keep
        regex: ...
        source_labels: [__meta_docker_container_name]
