from typing import Protocol, TypeVar, Iterable, Any, Dict

_Entity = TypeVar('_Entity')


class ReadRepositoryPort(Protocol[_Entity]):
    def get_all(self) -> Iterable[_Entity]: ...
    def get_by_id(self, id_: int) -> _Entity: ...
    def get_by_fields(self, **fields: Dict[str, Any]) -> _Entity: ...
    def filter_by_fields(self, **filters: Any) -> Iterable[_Entity]: ...


class CreateRepositoryPort(Protocol[_Entity]):
    def create(self, **fields: Dict[str, Any]) -> _Entity: ...
