server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ...
    basic_auth:
      username: ...
      password: ...

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginxlogs
          __path__: /var/log/nginx/*.log
    pipeline_stages:
      -   labeldrop:
            - filename
